name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt build pyinstaller cyclonedx-bom
      - name: Run smoke tests
        run: |
          python smoke_test.py
      - name: Build distributions
        run: |
          python -m build --sdist --wheel
          pyinstaller --onefile --name jwt_tool_cli jwt_tool.py || true
          pyinstaller --onefile --windowed --name jwt_tool_gui jwt_tool_standalone.py || true
      - name: Generate SBOM
        run: |
          cyclonedx-bom -o sbom.json -e requirements.txt || true
      - name: Checksums
        run: |
          shasum -a 256 dist/* > checksums.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jwt_tool_artifacts
          path: |
            dist/*
            sbom.json
            checksums.txt
            CHANGELOG.md
            SECURITY_NOTICE.md
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*
            sbom.json
            checksums.txt
            CHANGELOG.md
            SECURITY_NOTICE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
